### ISSUE TITLE
duplicate entry: org/apache/xmlbeans/xml/stream/Location.class

### ISSUE THREAD

**Issue by thugcee** [pjfanning/xmlbeans#7]
I'm using it in OSGi container. When bnd wraps xmlbean jar into bundle I get following error:
```Unable to wrap xmlbeans-2.6.1.jar
java.util.zip.ZipException: duplicate entry: org/apache/xmlbeans/xml/stream/Location.class
```
Why there are 2 Location classes?

**Comment by pjfanning** [comment]
Looks like the XMLBeans-499 fix in com.github.pjfanning:xmlbeans:2.6.2 was removed in 2.6.4.
Could you try 2.6.2 or 2.6.3?
I'll see about releasing a 2.6.5 that reapplies the fix.

**Comment by thugcee** [comment]
2.6.3 is OK, Thx :)
